In [1]:
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Query local DataFrames with SQL

https://www.ers.usda.gov/data-products/wheat-data

In [2]:
%pip install python-calamine

Requirement already satisfied: python-calamine in /usr/local/google/home/swast/src/github.com/googleapis/google-cloud-python/packages/bigframes/venv/lib/python3.14/site-packages (0.6.2)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [8]:
!wget -O /tmp/wheat-data.xlsx 'https://www.ers.usda.gov/media/5706/wheat-data-all-years.xlsx?v=19753'

--2026-04-06 19:39:12--  https://www.ers.usda.gov/media/5706/wheat-data-all-years.xlsx?v=19753
Resolving www.ers.usda.gov (www.ers.usda.gov)... 20.141.137.224
Connecting to www.ers.usda.gov (www.ers.usda.gov)|20.141.137.224|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 972455 (950K) [application/vnd.openxmlformats-officedocument.spreadsheetml.sheet]
Saving to: ‘/tmp/wheat-data.xlsx’

/tmp/wheat-data.xls 100%[===================>] 949.66K  2.00MB/s    in 0.5s

2026-04-06 19:39:13 (2.00 MB/s) - ‘/tmp/wheat-data.xlsx’ saved [972455/972455]

In [ ]:
import pandas as pd

df = pd.read_excel(
    "/tmp/wheat-data.xlsx",
    sheet_name="Table06",
    header=1,

    # Requires that the python-calamine project is also installed.
    engine="calamine",

    # Recommended so that string columns don't contain NaN, which can confuse
    # parquet serialization, which we use to read these data in BigQuery SQL.
    dtype_backend="pyarrow",
)
df

,Marketing year 1/,Type 2/,Beginning stocks,Production,Imports,Total supply 3/ 4/,Food use,Seed use,Feed and residual use,Total domestic use 4/,Exports,Total disappearance 4/,Ending stocks
0,1950/51,All wheat,496.0,1019.0,11,1526.0,580.0,--,109.0,689.0,345.0,1034.0,492.0
1,1951/52,All wheat,492.0,988.0,30,1510.0,585.0,--,110.0,695.0,485.0,1180.0,330.0
2,1952/53,All wheat,330.0,1306.0,24,1660.0,578.0,--,78.0,656.0,332.0,988.0,672.0
3,1953/54,All wheat,672.0,1173.0,6,1851.0,556.0,--,87.0,643.0,214.0,857.0,994.0
4,1954/55,All wheat,994.0,984.0,3,1981.0,552.0,--,53.0,605.0,267.0,872.0,1109.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,"2/ Hard Red Winter, Hard Red Spring, Soft Red ...",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
288,3/ Includes flour and selected other products ...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
289,4/ Totals may not add due to rounding.,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
290,"Source: USDA, Economic Research Service, based...",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
291,"Updated: March 13, 2026",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [14]:
import bigframes.pandas as bpd

# TODO(developer): Follow the instructions at
# https://docs.cloud.google.com/bigquery/docs/sandbox and set the project to the
# ID of the project you created.
bpd.options.bigquery.project = "swena-bq-sandbox"

In [15]:
bpd.read_pandas(df)

,Marketing year 1/,Type 2/,Beginning stocks,Production,Imports,Total supply 3/ 4/,Food use,Seed use,Feed and residual use,Total domestic use 4/,Exports,Total disappearance 4/,Ending stocks
0,1950/51,All wheat,496.0,1019.0,11,1526.0,580.0,--,109.0,689.0,345.0,1034.0,492.0
1,1951/52,All wheat,492.0,988.0,30,1510.0,585.0,--,110.0,695.0,485.0,1180.0,330.0
2,1952/53,All wheat,330.0,1306.0,24,1660.0,578.0,--,78.0,656.0,332.0,988.0,672.0
3,1953/54,All wheat,672.0,1173.0,6,1851.0,556.0,--,87.0,643.0,214.0,857.0,994.0
4,1954/55,All wheat,994.0,984.0,3,1981.0,552.0,--,53.0,605.0,267.0,872.0,1109.0
5,1955/56,All wheat,1109.0,937.0,10,2056.0,553.0,--,51.0,604.0,322.0,926.0,1130.0
6,1956/57,All wheat,1130.0,1005.0,8,2143.0,541.0,--,57.0,598.0,541.0,1139.0,1004.0
7,1957/58,All wheat,1004.0,956.0,10,1970.0,547.0,--,43.0,590.0,418.0,1008.0,962.0
8,1958/59,All wheat,962.0,1457.0,8,2427.0,561.0,--,48.0,609.0,450.0,1059.0,1368.0
9,1959/60,All wheat,1368.0,1118.0,7,2493.0,558.0,--,49.0,607.0,502.0,1109.0,1384.0